dist: trusty
sudo: false

env:
  - PACKER_VERSION="0.12.2"

rvm:
  - 2.3.1

branches:
  only:
    - master

before_install:
  - wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
  - unzip -d packer packer_${PACKER_VERSION}_linux_amd64.zip
  - touch VMwareTools-10.1.0-4449150.tar.gz

before_script: export PATH=$PATH:$PWD/packer

script: bento normalize
