dist: trusty
sudo: false

env:
  global:
    - PACKER_VERSION="1.0.2"
    - PATH=$HOME/bin:$PATH

rvm:
  - 2.4.1

branches:
  only:
    - master

before_install:
  - wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
  - unzip -d ~/bin packer_${PACKER_VERSION}_linux_amd64.zip

before_script:
  - packer --version

script: bento normalize
