# Documentation available at https://expeditor.chef.io/docs/getting-started/

# Slack channel in Chef Software slack to send notifications about build failures, etc
slack:
  notify_channel: chef-notify

github:
  delete_branch_on_merge: true
